// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBYmCbTpIcJ32GWpbJ62mTnlUN1n4OOec',
    appId: '1:322913084248:android:942b1d8dd058e8300cfb2d',
    messagingSenderId: '322913084248',
    projectId: 'prim-wear',
    storageBucket: 'prim-wear.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKX-7GO8fL_BW_NZjhmJPZ1UZPhH28qGU',
    appId: '1:322913084248:ios:064a97b0b4e88dff0cfb2d',
    messagingSenderId: '322913084248',
    projectId: 'prim-wear',
    storageBucket: 'prim-wear.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKX-7GO8fL_BW_NZjhmJPZ1UZPhH28qGU',
    appId: '1:322913084248:ios:064a97b0b4e88dff0cfb2d',
    messagingSenderId: '322913084248',
    projectId: 'prim-wear',
    storageBucket: 'prim-wear.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBepgebKtlRmnnYemFQqN77XD95nGWWNkA',
    appId: '1:322913084248:web:6e024aa405e07a0f0cfb2d',
    messagingSenderId: '322913084248',
    projectId: 'prim-wear',
    authDomain: 'prim-wear.firebaseapp.com',
    storageBucket: 'prim-wear.appspot.com',
  );
}
